# indexing / sllicing

 - 1차원 indexing : list 동일형
 - 2,3차 indexing
 - boolean indexing

In [1]:

import numpy as np

# 1. indexing
'''
1차원 : obj[index]
2차원 : obj[행,열]
3차원 : obj[면,행,열]
'''

# 1) list 객체
ldata = [0,1,2,3,4,5]
ldata[:]
ldata[2:]
ldata[:3]
ldata[-1]

# 2) numpy 객체
arr1d = np.array(ldata)
arr1d.shape
arr1d[2:]
arr1d[:3]
arr1d[-1]



# 2. slicing
arr = np.array(range(1,11))
arr # array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr_sl = arr[4:8]
arr_sl # array([5, 6, 7, 8])


# 블럭 수정
arr_sl[:] = 50
arr_sl # array([50, 50, 50, 50])


# 2,3차 indexing
arr2d = np.array([[1,2,3],[2,3,4],[3,4,5]])
arr2d.shape # (3,3)
arr2d 
'''
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])
'''


# 행 index : default
arr2d[1] # arr2d[1,:] -> [2,3,4]
arr2d[1:] # 2~3행
arr2d[:,1:]
arr2d[2,1]
arr2d[:2,1:]



# [면,행,열] 면 index : default
arr3d = np.array([[[1,2,3],[2,3,4],[3,4,5]],[[2,3,4],[3,4,5],[6,7,8]]])
arr3d
'''
array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]]])
'''
arr3d.shape # (2,3,3)
arr3d[0] # 1면
arr3d[1] # 2면

# 면 -> 행 index
arr3d[0,2] # [3,4,5]

# 면 -> 행 -> 열 index
arr3d[1,2,2] # 8





# 4. boolean indexing
dataset = np.random.randint(1,10,size=100)
len(dataset) # 100

# 5 이상
dataset2 = dataset[dataset >= 5]
len(dataset2) # 61
dataset2

# 5~8 자료 선택
# dataset[dataset >= 5 and dataset <= 8] : error
np.logical_and
np.logical_or
np.logical_not

dataset[np.logical_and(dataset >= 5, dataset <= 8)] 



array([8, 5, 6, 8, 8, 5, 7, 5, 8, 5, 5, 6, 7, 5, 5, 5, 7, 5, 8, 5, 8, 5,
       5, 6, 8, 6, 6, 8, 5, 7, 8, 7, 8, 5, 5, 6, 6, 8, 6, 5, 6, 7, 7])